{"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"serverError"},{"kind":"text","text":"("},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"externalID":"s:21IdentityOrchestration17TSIdoJourneyErrorO06serverE0yACs0E0_pSgcACmF","symbolKind":"case","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"serverError"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?)"}],"title":"TSIdoJourneyError.serverError(_:)","role":"symbol","modules":[{"name":"IdentityOrchestration"}]},"sections":[],"abstract":[{"text":"The server returned an unexpected error.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration","doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/TSIdoJourneyError"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/identityorchestration\/tsidojourneyerror\/servererror(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/TSIdoJourneyError\/serverError(_:)","interfaceLanguage":"swift"},"references":{"doc://com.TransmitSecurity.IdentityOrchestration/documentation/IdentityOrchestration/TSIdoJourneyError/serverError(_:)":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverError"},{"kind":"text","text":"("},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"url":"\/documentation\/identityorchestration\/tsidojourneyerror\/servererror(_:)","role":"symbol","abstract":[{"text":"The server returned an unexpected error.","type":"text"}],"type":"topic","title":"TSIdoJourneyError.serverError(_:)","kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/TSIdoJourneyError\/serverError(_:)"},"doc://com.TransmitSecurity.IdentityOrchestration/documentation/IdentityOrchestration":{"kind":"symbol","role":"collection","identifier":"doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration","type":"topic","url":"\/documentation\/identityorchestration","abstract":[],"title":"IdentityOrchestration"},"doc://com.TransmitSecurity.IdentityOrchestration/documentation/IdentityOrchestration/TSIdoJourneyError":{"type":"topic","title":"TSIdoJourneyError","abstract":[{"type":"text","text":"The enum for the start Journey errors."}],"identifier":"doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/TSIdoJourneyError","url":"\/documentation\/identityorchestration\/tsidojourneyerror","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"TSIdoJourneyError","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"TSIdoJourneyError","kind":"identifier"}],"kind":"symbol"}}}