{"kind":"symbol","identifier":{"url":"doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/TSIdoJourneyError\/serverError(_:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration","doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/TSIdoJourneyError"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"serverError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"The server returned an unexpected error."}],"metadata":{"modules":[{"name":"IdentityOrchestration"}],"roleHeading":"Case","externalID":"s:21IdentityOrchestration17TSIdoJourneyErrorO06serverE0yACs0E0_pSgcACmF","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"serverError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?)","kind":"text"}],"symbolKind":"case","role":"symbol","title":"TSIdoJourneyError.serverError(_:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/identityorchestration\/tsidojourneyerror\/servererror(_:)"]}],"references":{"doc://com.TransmitSecurity.IdentityOrchestration/documentation/IdentityOrchestration":{"title":"IdentityOrchestration","kind":"symbol","type":"topic","identifier":"doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration","role":"collection","abstract":[],"url":"\/documentation\/identityorchestration"},"doc://com.TransmitSecurity.IdentityOrchestration/documentation/IdentityOrchestration/TSIdoJourneyError":{"kind":"symbol","url":"\/documentation\/identityorchestration\/tsidojourneyerror","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TSIdoJourneyError","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"The enum for the start Journey errors."}],"title":"TSIdoJourneyError","identifier":"doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/TSIdoJourneyError","navigatorTitle":[{"text":"TSIdoJourneyError","kind":"identifier"}]},"doc://com.TransmitSecurity.IdentityOrchestration/documentation/IdentityOrchestration/TSIdoJourneyError/serverError(_:)":{"title":"TSIdoJourneyError.serverError(_:)","type":"topic","url":"\/documentation\/identityorchestration\/tsidojourneyerror\/servererror(_:)","abstract":[{"text":"The server returned an unexpected error.","type":"text"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"serverError","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.TransmitSecurity.IdentityOrchestration\/documentation\/IdentityOrchestration\/TSIdoJourneyError\/serverError(_:)"}}}